#!/bin/bash

wget https://factorio.com/get-download/stable/headless/linux64
cp /opt/factorio/server-adminlist.json ~
cp /opt/factorio/data/server-settings.json ~
cp /opt/factorio/data/server-whitelist.json ~
mv /opt/factorio/saves ~
sudo rm -rf /opt/factorio
tar -xvf ~/linux64
mv ~/server-adminlist.json ~/factorio/
mv ~/server-settings.json ~/factorio/data/
mv ~/server-whitelist.json ~/factorio/data/
sudo mv ~/factorio /opt/
/opt/factorio/bin/x64/factorio --use-server-whitelist --server-whitelist /opt/factorio/data/server-whitelist.json --server-settings /opt/factorio/data/server-settings.json --start-server /opt/factorio/saves/zc.zip --port 34197
